# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'
strategy:
  matrix:
    Python38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    addToPath: True

  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install robotframework==3.2.1 robotframework-seleniumlibrary==3.3.1 selenium==3.141.0 urllib3==1.25.9 &&  npm install chromedriver
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest robot Testcases\Tc2.robot
  displayName: 'pytest'

- powershell: robot --pythonpath . -x outputxunit.xml Testcases\Tc2.robot
 

